### ISSUE TITLE
NumberFormat Error when trying to create a new test

### ISSUE THREAD

**Issue by Toldwin** [bolorundurowb/Open-Exam-Suite#106]
![image](https://user-images.githubusercontent.com/12753133/198548359-a325febf-3758-4001-a410-3555a3287eef.png)
![image](https://user-images.githubusercontent.com/12753133/198548655-8802bfb4-94e4-4c7d-9d31-a0cd7b3f4bf9.png)

Thanks for your work !

For information I had this error every time when I tryed to create a new exam. So it is totaly impossible to create a test...
I also tryed numeric and textual values in all the fields without succes.

Best regards

**Comment by bolorundurowb** [comment]
@Toldwin , I was not able to replicate the issue  with the latest version of the app

<img width="1031" height="793" alt="Image" src="https://github.com/user-attachments/assets/0e6cd863-cb1b-476d-87df-b1aa1cae243c" />

It is possibly a locale issue, what locale are you using. I am using en-NG

**Comment by Toldwin** [comment]
Hi ! 

Thanks for your reply.

I'm using : fr-FR

<img width="1128" height="222" alt="Image" src="https://github.com/user-attachments/assets/a9a84f8b-c73a-4bb4-9245-96c4c6a10104" />

But this bug is realy old I think you can close it. Dont waste time... I made you this feedback because I find it important to help projet growth.

Best regards

**Comment by Toldwin** [comment]
But for info I still have the issue and it looks like it's linked with the hardcoded 4.0 version so should happend for everyone. Strange... 

<img width="2048" height="1578" alt="Image" src="https://github.com/user-attachments/assets/3bc3819c-1390-4449-8c87-b15158d3eb1f" />

**Comment by Toldwin** [comment]
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.FormatException: The input string '4.0' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Single.Parse(String s)
   at OpenExamSuite.Creator.GUI.HomeUi.SaveProperties(Object sender, EventArgs e) in D:\a\Open-Exam-Suite\Open-Exam-Suite\src\Apps\Creator\GUI\HomeUi.cs:line 743
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, UInt32 msg, WPARAM wparam, LPARAM lparam)


************** Assemblys chargés **************
System.Private.CoreLib
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Private.CoreLib.dll
----------------------------------------
OpenExamSuite.Creator
    Version de l’assembly : 4.0.1.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\OpenExamSuite.Creator.dll
----------------------------------------
System.Runtime
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Runtime.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Version de l’assembly : 9.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Microsoft.Extensions.DependencyInjection.dll
----------------------------------------
System.ComponentModel
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.ComponentModel.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Version de l’assembly : 9.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Microsoft.Extensions.DependencyInjection.Abstractions.dll
----------------------------------------
System.Windows.Forms
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Windows.Forms.dll
----------------------------------------
OpenExamSuite.Storage
    Version de l’assembly : 4.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\OpenExamSuite.Storage.dll
----------------------------------------
System.ComponentModel.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Private.Windows.Core
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Private.Windows.Core.dll
----------------------------------------
System.Private.Windows.GdiPlus
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Private.Windows.GdiPlus.dll
----------------------------------------
System.Drawing.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Threading.dll
----------------------------------------
System.Collections
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Collections.dll
----------------------------------------
System.Collections.Concurrent
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.Tracing
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Diagnostics.Tracing.dll
----------------------------------------
System.Drawing.Common
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Version de l’assembly : 4.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Numerics.Vectors
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\fr\System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Memory.dll
----------------------------------------
System.Drawing
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Drawing.dll
----------------------------------------
System.ObjectModel
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.ObjectModel.dll
----------------------------------------
System.Private.Uri
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Private.Uri.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Version de l’assembly : 8.1.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Formats.Nrbf
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Formats.Nrbf.dll
----------------------------------------
System.Text.Encoding.Extensions
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Reflection.Metadata
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Collections.Immutable.dll
----------------------------------------
System.Linq
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Linq.dll
----------------------------------------
System.Net.Http
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Security.Cryptography.dll
----------------------------------------
System.Collections.NonGeneric
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Collections.NonGeneric.dll
----------------------------------------
LiteDB
    Version de l’assembly : 5.0.21.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\LiteDB.dll
----------------------------------------
netstandard
    Version de l’assembly : 2.1.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\netstandard.dll
----------------------------------------
System.Text.RegularExpressions
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Text.RegularExpressions.dll
----------------------------------------
System.Buffers
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Buffers.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Reflection.Primitives.dll
----------------------------------------
System.Linq.Expressions
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Linq.Expressions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l’assembly : 0.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\
----------------------------------------
Microsoft.Win32.Registry
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\Microsoft.Win32.Registry.dll
----------------------------------------
OpenExamSuite.Core
    Version de l’assembly : 4.0.1.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\OpenExamSuite.Core.dll
----------------------------------------
OpenExamSuite.Shared.WinForms
    Version de l’assembly : 4.0.1.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\OpenExamSuite.Shared.WinForms.dll
----------------------------------------
System.Diagnostics.StackTrace
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.Diagnostics.StackTrace.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Version de l’assembly : 10.0.0.0
    Emplacement : C:\Program Files\Open Exam Suite\Creator\System.IO.MemoryMappedFiles.dll
----------------------------------------

************** Débogage JIT **************
